catalogue:
  aliases:
    - catalogue
    - tags
payment:
  aliases:
    - health
    - paymentAuth
orders:
  aliases:
    - orders
user:
  aliases:
    - login
    - register
    - customers
    - cards
    - addresses

