version: '2'

services:
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    hostname: catalogue
    restart: always
    ports:
      - "8051-8053:80"
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  payment:
    image: weaveworksdemos/payment:0.4.3
    hostname: payment
    restart: always
    ports:
      - "8054-8057:80"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
#  edge-router:
#    container_name: my-edge-router
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: my-edge-router:latest
#    ports:
#      - "8000:8000"
