version: '3'

services:
  dmon:
    image: softarch2021/dmon:latest
    hostname: dmon
    restart: always
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: -i weave -n weave -t 2
    depends_on:
      - catalogue
      - payment
      - orders
      - user
      - carts
      - shipping
  apigateway:
    build: ../apigateway
    hostname: apigateway
    restart: always
    dns: 172.17.0.1
    dns_search: weave.local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - monitoring
      - internal
    depends_on:
      - registry
  registry:
    build: ../registry
    hostname: registry
    restart: always
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    networks:
      - internal
    environment:
      - REDIS_HOST=172.17.0.1
      - LB_STRATEGY=rr # rr | random
  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    hostname: catalogue
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    deploy:
      mode: replicated
      replicas: $REPLICA_FACTOR
      placement:
        constraints: [node.role == worker]
    networks:
      - external
      - monitoring
  cat-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    networks:
      - external
  orders:
    image: weaveworksdemos/orders:0.4.7
    hostname: orders
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    deploy:
      mode: replicated
      replicas: $REPLICA_FACTOR
      placement:
        constraints: [node.role == worker]
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - monitoring
      - internal
      - secure
      - backoffice
  ord-db:
    image: mongo:3.4
    hostname: orders-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - internal
  payment:
    image: weaveworksdemos/payment:0.4.3
    hostname: payment
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    deploy:
      mode: replicated
      replicas: $REPLICA_FACTOR
      placement:
        constraints: [node.role == worker]
    networks:
      - secure
      - monitoring
  user:
    image: weaveworksdemos/user:0.4.4
    hostname: user
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    deploy:
      mode: replicated
      replicas: $REPLICA_FACTOR
      placement:
        constraints: [node.role == worker]
    environment:
      - MONGO_HOST=user-db:27017
      - reschedule=on-node-failure
    networks:
      - secure
      - monitoring
  usr-db:
    image: weaveworksdemos/user-db:0.4.0
    hostname: user-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - secure
  carts:
    image: weaveworksdemos/carts:0.4.8
    hostname: carts
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    deploy:
      mode: replicated
      replicas: $REPLICA_FACTOR
      placement:
        constraints: [node.role == worker]
    networks:
      - internal
      - monitoring
  crts-db:
    image: mongo:3.4
    hostname: carts-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - internal
  shipping:
    image: weaveworksdemos/shipping:0.4.8
    hostname: shipping
    restart: always
    dns: 172.17.0.1
    dns_search: weave.local
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    deploy:
      mode: replicated
      replicas: $REPLICA_FACTOR
      placement:
        constraints: [node.role == worker]
    networks:
      - backoffice
      - monitoring
  queue-master:
    image: weaveworksdemos/queue-master:0.3.1
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - backoffice
  rabbitmq:
    image: rabbitmq:3.6.8
    hostname: rabbitmq
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - backoffice
networks:
  external:
    driver: bridge
  internal:
    driver: bridge
  backoffice:
    driver: bridge
  secure:
    driver: bridge
  monitoring:
    driver: weavemesh
