version: '3'

services:
  dmon:
    image: softarch2021/dmon:latest
    hostname: dmon
    restart: always
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: -i weave -n weave,ml_sd_tradeoff_external -t 1,1
    depends_on:
      - catalogue
      - payment
      - orders
  apigateway:
    build: ../apigateway
    hostname: apigateway
    restart: always
    dns: 172.17.0.1
    dns_search: weave.local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - monitoring
      - internal
    depends_on:
      - registry
  registry:
    build: ../registry
    hostname: registry
    restart: always
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    networks:
      - internal
    environment:
      - REDIS_HOST=172.17.0.1
    depends_on:
      - dmon
  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    hostname: catalogue
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
    networks:
      - external
      - monitoring
  cat-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    networks:
      - external
  orders:
    image: weaveworksdemos/orders:0.4.7
    hostname: orders
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - monitoring
      - internal
      - secure
      - backoffice
  ord-db:
    image: mongo:3.4
    hostname: orders-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - internal
  payment:
    image: weaveworksdemos/payment:0.4.3
    hostname: payment
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
    networks:
      - secure
      - monitoring
networks:
  external:
    driver: bridge
  internal:
    driver: bridge
  backoffice:
    driver: bridge
  secure:
    driver: bridge
  monitoring:
    driver: weavemesh
