"""empty message

Revision ID: 7ecfa3632f0f
Revises: d02d6bf3e894
Create Date: 2022-05-26 11:02:58.024805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecfa3632f0f'
down_revision = 'd02d6bf3e894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workloads', sa.Column('label', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workloads', 'label')
    # ### end Alembic commands ###
