"""empty message

Revision ID: 9bb73abdb751
Revises: 2299e289b126
Create Date: 2022-04-27 15:50:00.276601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb73abdb751'
down_revision = '2299e289b126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_status', sa.Column('service_instance', sa.String(length=100), nullable=True))
    op.drop_column('service_status', 'service_instance_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_status', sa.Column('service_instance_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('service_status', 'service_instance')
    # ### end Alembic commands ###
