"""empty message

Revision ID: a762cbd34380
Revises: fa6cc75e6bc1
Create Date: 2022-09-16 18:50:56.010154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a762cbd34380'
down_revision = 'fa6cc75e6bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_status', sa.Column('energy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_status', 'energy')
    # ### end Alembic commands ###
