"""empty message

Revision ID: d02d6bf3e894
Revises: 55cb35f4b9fd
Create Date: 2022-05-17 17:42:17.817902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02d6bf3e894'
down_revision = '55cb35f4b9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
