"""empty message

Revision ID: fb0bb5a4b6f7
Revises: 9bb73abdb751
Create Date: 2022-05-09 17:23:02.531390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0bb5a4b6f7'
down_revision = '9bb73abdb751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_call', sa.Column('service_type', sa.String(length=100), nullable=True))
    op.add_column('service_status', sa.Column('service_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_status', 'service_type')
    op.drop_column('service_call', 'service_type')
    # ### end Alembic commands ###
